---@class FeyConfigOpts
local DefaultConfig = {
  -- MY NEW OPTIONS
  -- TODO: Document these!
  -- TODO: Validate these! (vim.validate())
  --
  -- TODO: verify list is no empty
  fey_default_subheading_index_order = { 'roman_upper', 'alpha_upper', 'roman_lower', 'alpha_lower' },
  -- fey_default_subheading_delimiter_order = { '.', ':', ';' },
  fey_default_subheading_delimiter_order = {}, -- empty list or nil means use last value
  fey_default_subheading_delimiter = '.',
  fey_subheadings_unique_segments_for_subtree = false,
  fey_use_uppercase_for_binary_marker = false,
  fey_use_uppercase_for_hex_marker = false,
  fey_use_uppercase_for_hex_index = false,
  -- --

  fey_agenda_files = '',
  fey_default_notes_file = '',
  fey_todo_keywords = { 'TODO', '|', 'DONE' },
  fey_todo_repeat_to_state = nil,
  fey_todo_keyword_faces = {},
  fey_deadline_warning_days = 14,
  fey_agenda_min_height = 16,
  fey_agenda_span = 'week', -- day/week/month/year/number of days
  fey_agenda_start_on_weekday = 1,
  fey_agenda_start_day = nil, -- start from today + this modifier
  calendar_week_start_day = 1,
  calendar = {
    round_min_with_hours = true,
    min_big_step = 15,
  },
  fey_capture_templates = {
    t = {
      description = 'Task',
      template = '* TODO %?\n  %u',
    },
  },
  fey_startup_folded = 'overview',
  fey_agenda_skip_scheduled_if_done = false,
  fey_agenda_skip_deadline_if_done = false,
  fey_agenda_text_search_extra_files = {},
  fey_agenda_custom_commands = {},
  fey_agenda_hide_empty_blocks = false,
  fey_agenda_block_separator = '-',
  fey_agenda_sorting_strategy = {
    agenda = { 'time-up', 'priority-down', 'category-keep' },
    todo = { 'priority-down', 'category-keep' },
    tags = { 'priority-down', 'category-keep' },
  },
  fey_agenda_remove_tags = false,
  fey_agenda_time_grid = {
    type = { 'daily', 'today', 'require-timed' },
    times = { 800, 1000, 1200, 1400, 1600, 1800, 2000 },
    time_separator = '┄┄┄┄┄',
    time_label = '┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄',
  },
  fey_agenda_current_time_string = '<- now -----------------------------------------------',
  fey_agenda_use_time_grid = true,
  fey_agenda_show_future_repeats = true,
  fey_priority_highest = 'A',
  fey_priority_default = 'B',
  fey_priority_lowest = 'C',
  fey_priority_start_cycle_with_default = true,
  fey_archive_location = '%s_archive::',
  fey_tags_column = -80,
  fey_use_tag_inheritance = true,
  fey_tags_exclude_from_inheritance = {},
  fey_hide_leading_signature = false,
  fey_hide_emphasis_markers = false,
  fey_ellipsis = '...',
  fey_log_done = 'time',
  fey_log_repeat = 'time',
  fey_log_into_drawer = nil,
  fey_highlight_latex_and_related = nil,
  fey_custom_exports = {},
  fey_adapt_indentation = false,
  fey_startup_indented = false,
  fey_indent_mode_turns_off_fey_adapt_indentation = true,
  fey_indent_mode_turns_on_hiding_signature = true,
  fey_time_stamp_rounding_minutes = 5,
  fey_cycle_separator_lines = 2,
  fey_blank_before_new_entry = {
    heading = true,
    list_item = false,
  },
  fey_src_window_setup = 'top 16new',
  fey_edit_src_content_indentation = 0,
  fey_edit_src_filetype_map = {},
  fey_id_uuid_program = 'uuidgen',
  fey_id_ts_format = '%Y%m%d%H%M%S',
  fey_id_method = 'uuid',
  fey_id_prefix = nil,
  fey_id_link_to_fey_use_id = false,
  fey_use_property_inheritance = false,
  fey_babel_default_header_args = {
    [':tangle'] = 'no',
    [':noweb'] = 'no',
  },
  win_split_mode = 'horizontal',
  win_border = 'single',
  notifications = {
    enabled = false,
    cron_enabled = true,
    repeater_reminder_time = false,
    deadline_warning_reminder_time = 0,
    reminder_time = 10,
    deadline_reminder = true,
    scheduled_reminder = true,
  },
  hyperlinks = {
    sources = {},
  },
  mappings = {
    disable_all = false,
    fey_return_uses_meta_return = false,
    prefix = '<Leader>;',
    global = {
      --   fey_agenda = '<prefix>a',
      --   fey_capture = '<prefix>c',
    },
    agenda = {
      --   fey_agenda_later = 'f',
      --   fey_agenda_earlier = 'b',
      --   fey_agenda_goto_today = '.',
      --   fey_agenda_day_view = 'vd',
      --   fey_agenda_week_view = 'vw',
      --   fey_agenda_month_view = 'vm',
      --   fey_agenda_year_view = 'vy',
      --   fey_agenda_quit = 'q',
      --   fey_agenda_switch_to = '<CR>',
      --   fey_agenda_goto = '<TAB>',
      --   fey_agenda_goto_date = 'J',
      --   fey_agenda_redo = 'r',
      --   fey_agenda_todo = 't',
      --   fey_agenda_open_at_point = '<prefix>o',
      --   fey_agenda_clock_goto = '<prefix>xj',
      --   fey_agenda_set_effort = '<prefix>xe',
      --   fey_agenda_clock_in = 'I',
      --   fey_agenda_clock_out = 'O',
      --   fey_agenda_clock_cancel = 'X',
      --   fey_agenda_clockreport_mode = 'R',
      --   fey_agenda_priority = '<prefix>,',
      --   fey_agenda_priority_up = '+',
      --   fey_agenda_priority_down = '-',
      --   fey_agenda_archive = '<prefix>$',
      --   fey_agenda_toggle_archive_tag = '<prefix>A',
      --   fey_agenda_set_tags = '<prefix>t',
      --   fey_agenda_deadline = '<prefix>id',
      --   fey_agenda_schedule = '<prefix>is',
      --   fey_agenda_filter = '/',
      --   fey_agenda_refile = '<prefix>r',
      --   fey_agenda_add_note = '<prefix>na',
      --   fey_agenda_preview = 'K',
      --   fey_agenda_show_help = 'g?',
    },
    capture = {
      --   fey_capture_finalize = '<C-c>',
      --   fey_capture_refile = '<prefix>r',
      --   fey_capture_kill = '<prefix>k',
      --   fey_capture_show_help = 'g?',
    },
    note = {
      --   fey_note_finalize = '<C-c>',
      --   fey_note_kill = '<prefix>k',
    },
    fey = {
      -- fey_refile = '<prefix>r',
      -- fey_timestamp_up_day = '<S-UP>',
      -- fey_timestamp_down_day = '<S-DOWN>',
      -- fey_timestamp_up = '<C-a>',
      -- fey_timestamp_down = '<C-x>',
      -- fey_change_date = 'cid',
      -- fey_priority = '<prefix>,',
      -- fey_priority_up = 'ciR',
      -- fey_priority_down = 'cir',
      -- fey_todo = 'cit',
      -- fey_todo_prev = 'ciT',
      -- fey_toggle_checkbox = '<C-Space>',
      -- fey_toggle_heading = '<prefix>*',
      -- fey_open_at_point = '<prefix>o',
      -- fey_edit_special = [[<prefix>']],
      -- fey_add_note = '<prefix>na',
      -- fey_cycle = '<TAB>',
      -- fey_global_cycle = '<S-TAB>',
      -- fey_archive_subtree = '<prefix>$',
      -- fey_set_tags_command = '<prefix>t',
      -- fey_toggle_archive_tag = '<prefix>A',
      fey_fix_indentation = '<prefix>fi',
      fey_do_promote = '<>',
      fey_do_demote = '><',
      fey_promote_subtree = '<prefix>h',
      fey_demote_subtree = '<prefix>l',
      fey_move_subtree_up = '<prefix>k',
      fey_move_subtree_down = '<prefix>j',
      fey_meta_return = '<Leader><CR>', -- Add heading, item or row (context-dependent)
      fey_meta_sub_return = '<Leader><S-CR>', -- Add subheading, item or row (context-dependent)
      -- fey_return = '<CR>',
      -- fey_insert_heading_respect_content = '<prefix>ih', -- Add new heading after current heading block (same level)
      -- fey_insert_todo_heading = '<prefix>iT', -- Add new todo heading right after current heading (same level)
      -- fey_insert_todo_heading_respect_content = '<prefix>it', -- Add new todo heading after current heading block (same level)
      -- fey_export = '<prefix>e',
      -- fey_next_visible_heading = '}',
      -- fey_previous_visible_heading = '{',
      -- fey_forward_heading_same_level = ']]',
      -- fey_backward_heading_same_level = '[[',
      -- outline_up_heading = 'g{',
      -- fey_deadline = '<prefix>id',
      -- fey_schedule = '<prefix>is',
      -- fey_time_stamp = '<prefix>i.',
      -- fey_time_stamp_inactive = '<prefix>i!',
      -- fey_toggle_timestamp_type = '<prefix>d!',
      -- fey_insert_link = '<prefix>li',
      -- fey_store_link = '<prefix>ls',
      -- fey_clock_in = '<prefix>xi',
      -- fey_clock_out = '<prefix>xo',
      -- fey_clock_cancel = '<prefix>xq',
      -- fey_clock_goto = '<prefix>xj',
      -- fey_set_effort = '<prefix>xe',
      -- fey_show_help = 'g?',
      -- fey_babel_tangle = '<prefix>bt',
    },
    edit_src = {
      --   fey_edit_src_abort = '<prefix>k',
      --   fey_edit_src_save = '<prefix>w',
      --   fey_edit_src_save_exit = [[<prefix>']],
      --   fey_edit_src_show_help = 'g?',
    },
    text_objects = {
      --   inner_heading = 'ih',
      --   around_heading = 'ah',
      --   inner_subtree = 'ir',
      --   around_subtree = 'ar',
      --   inner_heading_from_root = 'Oh',
      --   around_heading_from_root = 'OH',
      --   inner_subtree_from_root = 'Or',
      --   around_subtree_from_root = 'OR',
    },
  },
  emacs_config = {
    executable_path = 'emacs',
    config_path = nil,
  },
  ui = {
    folds = {
      colored = true,
    },
    menu = {
      handler = nil,
    },
    input = {
      use_vim_ui = false,
    },
    agenda = {
      preview_window = {
        wrap = false,
      },
    },
  },
}

return DefaultConfig
