#+OPTIONS: H:9 ^:nil
* Plugins

📝 NOTE: If you create a plugin for fey, make sure to tag it with =fey-nvim= on github and submit an issue/PR to add it to this list.

Fey supports various plugins to extend its functionality or make it more pretty and user friendly:

- [[#extend-fey][Extend fey]]
  - [[#fey-super-agendanvim][fey-super-agenda.nvim]]
  - [[#fey-roamnvim][fey-roam.nvim]]
  - [[#sniprun][sniprun]]
  - [[#fey-notebooknvim][fey-notebook.nvim]]
  - [[#telescope-feynvim][telescope-fey.nvim]]
  - [[#fey-linknvim][fey-link.nvim]]
  - [[#fey-cycle-litenvim][fey-cycle-lite.nvim]]
- [[#completion-plugins][Completion plugins]]
  - [[#blinkcmp][blink.cmp]]
  - [[#nvim-cmp][nvim-cmp]]
  - [[#rldxnvim][RLDX.nvim]]
- [[#aesthetics][Aesthetics]]
  - [[#fey-bulletsnvim][fey-bullets.nvim]]
  - [[#headingsnvim][headings.nvim]]
  - [[#fey-modernnvim][fey-modern.nvim]]
- [[#other][Other]]
- [[#example-configuration][Example configuration]]

** Extend fey
:PROPERTIES:
:CUSTOM_ID: extend-fey
:END:
*** fey-super-agenda.nvim
:PROPERTIES:
:CUSTOM_ID: fey-super-agendanvim
:END:
Link: [[https://github.com/hamidi-dev/fey-super-agenda.nvim][fey-super-agenda.nvim]]

This is the port of Emacs [[https://github.com/alphapapa/fey-super-agenda][fey-super-agenda]].
*** fey-roam.nvim
:PROPERTIES:
:CUSTOM_ID: fey-roamnvim
:END:
Link: [[https://github.com/chipsenkbeil/fey-roam.nvim][fey-roam.nvim]]

This is the port of Emacs [[https://www.feyroam.com/][fey-roam]].
*** sniprun
:PROPERTIES:
:CUSTOM_ID: sniprun
:END:
Link: [[https://github.com/michaelb/sniprun][sniprun]]

Plugin for code block evaluation.
*** fey-notebook.nvim
:PROPERTIES:
:CUSTOM_ID: fey-notebooknvim
:END:
Link: [[https://github.com/bitbloxhub/fey-notebook.nvim][fey-notebook.nvim]]

Jupyter notebooks for fey-babel.
*** telescope-fey.nvim
:PROPERTIES:
:CUSTOM_ID: telescope-feynvim
:END:
Link: [[https://github.com/Loreite/telescope-fey.nvim][telescope-fey.nvim]]

[[https://github.com/nvim-telescope/telescope.nvim][Telescope]] extension for fey that adds fuzzy finding of fey files, headings, etc.

*** fey-link.nvim
:PROPERTIES:
:CUSTOM_ID: fey-linknvim
:END:
Link: [[https://github.com/seflue/fey-link.nvim][fey-link.nvim]]

Extends fey's capabilities to insert and follow links.

*** fey-cycle-lite.nvim
:PROPERTIES:
:CUSTOM_ID: fey-cycle-litenvim
:END:
Link: [[https://github.com/aaratha/fey-cycle-lite.nvim][fey-cycle-lite.nvim]]

Plugin for doom-emacs style simple cycling ([[https://github.com/doomemacs/doomemacs/blob/master/modules/lang/fey/autoload/fey.el#L497][fey-cycle-only-current-subtree-h]])

** Completion plugins
:PROPERTIES:
:CUSTOM_ID: completion-plugins
:END:

📝 NOTE: There is experimental LSP support that provides the autocompletion. See [[file:./configuration.fey::#lsp][Lsp section]] for more details.

*** blink.cmp
:PROPERTIES:
:CUSTOM_ID: blinkcmp
:END:
Link:  [[https://github.com/Saghen/blink.cmp][blink.cmp]]

Add the fey provider and enable it for =fey= filetype.
#+begin_src lua
require('blink.cmp').setup({
  sources = {
    per_filetype = {
      fey = {'fey'}
    },
    providers = {
      fey = {
        name = 'Fey',
        module = 'fey.fey.autocompletion.blink',
        fallbacks = { 'buffer' },
      },
    },
  },
})
#+end_src

*** nvim-cmp
:PROPERTIES:
:CUSTOM_ID: nvim-cmp
:END:
Link: [[https://github.com/hrsh7th/nvim-cmp][nvim-cmp]]

Add the =fey= source to =nvim-cmp= ~sources~ list.
#+BEGIN_SRC lua
require('cmp').setup({
  sources = {
    { name = 'fey' }
  }
})
#+END_SRC

*** RLDX.nvim
:PROPERTIES:
:CUSTOM_ID: rldxnvim
:END:
Link: [[https://github.com/michhernand/RLDX.nvim][RLDX.nvim]]
1. Add [[https://github.com/michhernand/RLDX.nvim][RLDX.nvim]] plugin to Neovim.
2. Add the =cmp_rolodex= source to =nvim-cmp= ~sources~ list.
#+BEGIN_SRC lua
require('cmp').setup({
  sources = {
    { name = 'cmp_rolodex' }
  }
})
#+END_SRC

** Aestehtics
:PROPERTIES:
:CUSTOM_ID: aesthetics
:END:
*** fey-bullets.nvim
:PROPERTIES:
:CUSTOM_ID: fey-bulletsnvim
:END:
Link: [[https://github.com/Loreite/fey-bullets.nvim][fey-bullets.nvim]]
Port of Emacs [[https://github.com/sabof/fey-bullets][fey-bullets]].

Run after the fey setup.
#+BEGIN_SRC lua
-- Your fey setup
require('fey').setup()

--Setup fey-bullets
require('fey-bullets').setup()
#+END_SRC

*** headings.nvim
:PROPERTIES:
:CUSTOM_ID: headingsnvim
:END:
Link: [[https://github.com/lukas-reineke/headings.nvim][headings.nvim]]

Plugin that adds some additional highlights to headings.
#+BEGIN_SRC lua
-- Your fey setup
require('fey').setup()

--Setup headings.nvim
require("headings").setup()
#+END_SRC


*** fey-modern.nvim
:PROPERTIES:
:CUSTOM_ID: fey-modernnvim
:END:
Link: [[https://github.com/danilshvalov/fey-modern.nvim][fey-modern.nvim]]

Modern looking agenda prompt menu.
#+begin_src lua
local Menu = require("fey-modern.menu")

require("fey").setup({
  ui = {
    menu = {
      handler = function(data)
        Menu:new():open(data)
      end,
    },
  },
})
#+end_src

** Other
:PROPERTIES:
:CUSTOM_ID: other
:END:
To view all plugins that are tagged for =fey.nvim=, visit [[https://github.com/topics/fey-nvim][fey-nvim]] github tag.

📝 NOTE: If you create a plugin for fey, make sure to tag it with =fey-nvim= on github and submit an issue/PR to add it to this list.

** Example configuration
:PROPERTIES:
:CUSTOM_ID: example-configuration
:END:
Example configuration with few of these plugins using [[https://github.com/folke/lazy.nvim][lazy.nvim]]:
#+begin_src lua
{
  'Loreite/fey.nvim',
  dependencies = {
    'nvim-telescope/telescope.nvim',
    'Loreite/telescope-fey.nvim',
    'Loreite/fey-bullets.nvim',
    'Saghen/blink.cmp'
  },
  event = 'VeryLazy',
  config = function()
    require('fey').setup({
      fey_agenda_files = '~/feyfiles/**/*',
      fey_default_notes_file = '~/feyfiles/refile.fey',
    })
    require('fey-bullets').setup()
    require('blink.cmp').setup({})

    -- Experimental LSP support
    vim.lsp.enable('fey')
  end,
}
#+end_src
